### PR TITLE
support libressl

### PR DESCRIPTION
**Pull request by archerabi**
Build on alpine linux

### CODE REVIEW

**Comment by imsky** [comment]
do tests pass?

**Comment by archerabi** [comment]
the python ssl tests fail, but they are failing with openssl too. I will try it on ubuntu or debian and see if they work there.

**Comment by imsky** [comment]
cool would be good to know that tests pass on alpine before moving forward

**Comment by archerabi** [comment]
the test failures seem to stem from the fact that the included test certificates are not accepted by libressl. 

```
SSL_CTX_use_certificate_chain_file( /home/vagrant/qpid-proton/python/tests/proton_tests/ssl_db/server-certificate.pem ) failed
31: error:14FFF0F7:SSL routines:(UNKNOWN)SSL_internal:unknown certificate type
```

Not sure why that is so, and i don't have a fix for it. The ssl connection however seems to work properly as the ssl connection to aws amq is working.

**Comment by imsky** [comment]
are you testing under vagrant or docker? there may be slight differences in how the OS is setup

**Comment by archerabi** [comment]
Vagrant. not sure this is OS related though. Looks like libressl and openssl have diverged in the kinds of certificates and keys they support.  Looks like libressl is stricter in terms of minimum key length.

**Comment by imsky** [comment]
seems like we should figure it out before going to production

**Comment by imsky** [comment]
👍

**Comment by archerabi** [comment]
https://github.com/libressl-portable/portable/issues/440

**Comment by archerabi** [comment]
@imsky I had to update the certs to use RSA keys because libressl doesn't support DSA anymore [https://github.com/libressl-portable/portable/issues/440](link).

Now all the _core_ tests pass. The ones that fail are tests for examples. They fail because alpine doesn't let processes open port 443 for listening. Let me know if have ideas on fixing that.

**Comment by imsky** [comment]
example tests are probably fine. there may be a way to enable those ports, but doesn't seem critical

**Comment by imsky** [comment]
💸

**Comment by archerabi** [comment]
Thanks @imsky

**Pull request merged**
